In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.5304562 ,  0.00699773,  0.26413932,  0.5483905 ,  0.12698865,
        -0.41423345,  0.2671379 , -0.65223116, -0.11574718,  0.07845423]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.14994985, 0.08884049, 0.11489102, 0.15266337, 0.10016646,
        0.05830054, 0.11523605, 0.04595275, 0.07857846, 0.09542102]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.842144

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2938 - accuracy: 0.9142
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1411 - accuracy: 0.9584
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1080 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0891 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0737 - accuracy: 0.9768


In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0765 - accuracy: 0.9784 - 389ms/epoch - 1ms/step


[0.07649313658475876, 0.9783999919891357]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.6037338e-07, 5.3736153e-07, 2.3160872e-04, 1.2272021e-03,
        3.4255914e-11, 2.7978231e-07, 3.7267691e-13, 9.9852318e-01,
        1.0165924e-05, 6.8401046e-06],
       [1.1038286e-08, 1.4566894e-03, 9.9851292e-01, 2.8138333e-05,
        5.6171519e-17, 3.7932247e-07, 4.7558163e-10, 3.5959829e-11,
        1.9551255e-06, 1.5027312e-13],
       [9.9556314e-07, 9.9659973e-01, 3.5253851e-04, 4.1461455e-05,
        5.1641382e-06, 3.4837649e-05, 1.4789009e-05, 2.7356641e-03,
        2.1088560e-04, 3.9127704e-06],
       [9.9961251e-01, 1.3602695e-09, 3.2947143e-04, 3.3883290e-07,
        3.5705163e-08, 3.0608039e-06, 1.6769246e-06, 4.9698738e-05,
        1.5972898e-07, 3.0565595e-06],
       [6.0115184e-07, 5.9323235e-10, 1.5627700e-05, 8.7099066e-09,
        9.9901891e-01, 2.0810082e-06, 5.6377854e-07, 4.5479439e-05,
        6.3516296e-08, 9.1669522e-04]], dtype=float32)>