In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.58031714, -0.25826752,  0.18568698,  0.30366543, -0.243361  ,
        -0.01839192,  0.24742202, -0.66838145, -0.42542687, -0.04392925]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.17366943, 0.07508111, 0.1170409 , 0.13169675, 0.0762087 ,
        0.09543492, 0.12449413, 0.04982192, 0.06352349, 0.09302863]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.3493106

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2975 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1438 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1084 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0889 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0745 - accuracy: 0.9768


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0795 - accuracy: 0.9758 - 382ms/epoch - 1ms/step


[0.07949623465538025, 0.9757999777793884]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.30294299e-08, 8.95805041e-10, 3.52020070e-05, 4.25497536e-04,
        1.24042139e-12, 1.57214203e-07, 1.85945877e-13, 9.99537945e-01,
        4.13969644e-07, 7.21758340e-07],
       [6.25999519e-08, 2.86905233e-05, 9.99783218e-01, 1.87374972e-04,
        1.02457946e-13, 4.44169615e-07, 3.07785761e-08, 2.87040187e-14,
        1.61118621e-07, 2.46361921e-14],
       [2.45159072e-07, 9.98847365e-01, 2.25421958e-04, 6.37498806e-06,
        1.94940076e-04, 1.50633844e-06, 2.06955010e-05, 5.59496286e-04,
        1.42857651e-04, 1.14464558e-06],
       [9.99698877e-01, 3.33362071e-09, 2.82098335e-04, 6.60002911e-07,
        3.57533139e-07, 3.20692607e-06, 3.34153879e-06, 9.45764441e-06,
        2.40871429e-08, 1.95800772e-06],
       [4.89978333e-07, 2.80300072e-09, 1.73282024e-06, 7.60988073e-08,
        9.99121249e-01, 9.27836118e-06, 1.65539916e-07, 2.90724784e-05,
        4.41403745e-06, 8.33473634e-04]], dtype=float32)>